apiVersion: v1
kind: ReplicationController
metadata:
   name: rc
spec:
    replicas: 10
    template:
       metadata:
           name: rc-pod
           labels:
                app: rc
       spec:
          containers:
              - name: rc-container
                image: nginx
                  
