apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-dp
spec:
   replicas: 2
   selector:
      matchLabels:
            app: db
   template:
        metadata:
           name: httpd-pod
           labels:
              app: db
        spec:
           containers:
                 - name: con
                   image: centos/httpd
                   volumeMounts:
                       - mountPath: /var/www/html
                         name: httpd-vol
           volumes:
                - name: httpd-vol
                  persistentVolumeClaim:
                         claimName: mypvc             
