apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: container
        image: nginx
        volumeMounts:
        - name: my-nfs-volume
          mountPath: /usr/share/nginx/html
      volumes:
      - name: my-nfs-volume
        persistentVolumeClaim:
             claimName: my-nfs-pvc

