apiVersion: v1
kind: PersistentVolume
metadata: 
  name: mypv
spec:
  capacity:
      storage: 1Gi
  accessModes: 
        - ReadWriteMany
  volumeMode: Filesystem        
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  nfs:
    server: 192.168.23.128
    path: /nfsserver  
