apiVersion: v1
kind: Pod
metadata:
    name: pod
    labels:
       app: svc
spec:
     containers:
          - name: container1
            image: centos/httpd

---
apiVersion: v1
kind: Service
metadata:
  name: my-svc
spec:
   selector:
       app: svc
   type: NodePort
   ports: 
      - targetPort: 80
        nodePort: 31080
        port: 80  
