apiVersion: v1
kind: Pod
metadata:
   name: vol-pod
spec:
   containers:
       - name: con
         image: centos/httpd
         volumeMounts: 
              - mountPath: /var/www/html
                name: myvol
   volumes:
       - name: myvol
         persistentVolumeClaim:
                    claimName: pvc     
