apiVersion: v1
kind: PersistentVolume
metadata:
   name: pv
spec:
  accessModes:
    - ReadWriteMany  
  capacity:
      storage: 1Gi
  storageClassName: my-storage-class    
  hostPath:
      path: /httpd    
