apiVersion: v1
kind: PersistentVolumeClaim
metadata:
   name: pvc
spec:
   accessModes:
        - ReadWriteMany
   storageClassName: my-storage-class       
   resources:
       requests:
          storage: 700Mi  
