apiVersion: apps/v1
kind: Deployment
metadata:
    name: wp-dp
spec:
   selector:
       matchLabels:
         app: wp
   replicas: 2
   template:
       metadata:
           name: wp-pod
           labels:
              app: wp
       spec:
         containers:
              - name: wordpress
                image: wordpress
                env:
                   - name: WORDPRESS_DB_PASSWORD
                     value: "redhat"
                   - name: WORDPRESS_DB_USER
                     value: "root"
                   - name: WORDPRESS_DB_NAME
                     value: "sourabh"
                   - name: WORDPRESS_DB_HOST
                     value: "db-svc"    
